# Generated by Django 5.2.6 on 2025-09-23 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0004_subscriptionplan_duration_days_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadeddocument',
            name='doc_type',
            field=models.CharField(choices=[('GST', 'GST'), ('PAN', 'PAN'), ('FSSAI', 'FSSAI'), ('AADHAAR', 'AADHAAR'), ('UDYAM', 'UDYAM'), ('OTHER', 'Other')], default='OTHER', max_length=50),
        ),
    ]
