# Generated by Django 5.2.6 on 2025-09-23 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0005_alter_uploadeddocument_doc_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadeddocument',
            name='confidence',
            field=models.FloatField(default=0),
        ),
    ]
