# Generated by Django 5.2.6 on 2025-09-24 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0006_uploadeddocument_confidence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tokens',
            field=models.IntegerField(default=999999999),
        ),
    ]
