# Generated by Django 5.2.8 on 2026-04-02 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0007_alter_profile_tokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadeddocument',
            name='doc_type',
            field=models.CharField(choices=[('GST', 'GST'), ('PAN', 'PAN'), ('FSSAI', 'FSSAI'), ('AADHAAR', 'AADHAAR'), ('UDYAM', 'UDYAM'), ('DL', 'Driving License'), ('RC', 'Registration Certificate'), ('AGREEMENT', 'Agreement'), ('AFFIDAVIT', 'Affidavit'), ('RESUME', 'Resume/CV'), ('OTHER', 'Other')], default='OTHER', max_length=50),
        ),
    ]
